SC-383: R2131 sc 383 r4x
Sage-Bionetworks-IT/packer-rstudio pull request #78
Opened 2023-08-14 19:55 UTC by xschildw

This PR starts from 2.1.3 and just updates R and Python. It also moves from travis to GHA for deployment.

2023-08-14 19:56 UTC, xschildw commented on .github/workflows/deploy.yaml
> +    if: ${{ github.ref == 'refs/heads/2.1.3.1' || startsWith(github.ref, 'refs/tags/v') }}
Changed from master, I think the tag prefix should be 'refs/tags/v2.1.3'.

2023-08-15 16:19 UTC, zaro0508 requested changes

2023-08-15 16:19 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +    if: ${{ github.ref == 'refs/heads/2.1.3.1' || startsWith(github.ref, 'refs/tags/v') }}
you should  create a `v2.1.3` branch and set this to `ref/heads/v2.1.3`.  Then you should target this PR against the `v2.1.3` branch

2023-08-15 16:19 UTC, zaro0508 commented on src/playbook.yaml
> +        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
does this make python3.8 the default python?  don't we also need to set the default version with `update-alternatives --set python3 /usr/bin/python3.8`?

2023-08-15 17:15 UTC, xschildw commented on .github/workflows/deploy.yaml
> +    if: ${{ github.ref == 'refs/heads/2.1.3.1' || startsWith(github.ref, 'refs/tags/v') }}
OK

2023-08-15 17:15 UTC, xschildw commented on src/playbook.yaml
> +        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
The higher priority makes it the default but no harm in being explicit, will do.

2023-08-15 17:45 UTC, xschildw commented on .github/workflows/deploy.yaml
> +    if: ${{ github.ref == 'refs/heads/2.1.3' || startsWith(github.ref, 'refs/tags/v2.1.3') }}
Used 2.1.3 as GH warns about potential confusion if using same branch and tag name...

2023-08-15 18:19 UTC, zaro0508 requested changes

2023-08-15 18:19 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +    if: ${{ github.ref == 'refs/heads/2.1.3' || startsWith(github.ref, 'refs/tags/v2.1.3') }}
branch should be `v2.1.3` and condition should be `github.ref == 'refs/heads/v2.1.3'`

also i think you can leave tags condition as `startsWith(github.ref, 'refs/tags/v')`

2023-08-15 18:58 UTC, zaro0508 approved these changes

2023-08-15 19:14 UTC, merged